"""
LumenCloud ORM 模型（docs/新系统设计.md §3 契约落地，11 张业务表）

模型类名 → 表名映射：
    Media          → media               EpisodeState    → episode_state
    TransferQueue  → transfer_queue      DownloadTask    → download_task
    TaskRun        → task_run            QuarkCapacityLog → quark_capacity_log
    User           → users               InviteCode      → invite_codes
    WatchRequest   → watch_requests      Notification    → notifications
    SystemConfig   → system_config       TmdbCache       → tmdb_cache

全局约定（契约，其他模块依赖这些名字，勿改名）：
- 主键一律 BigInteger + Identity（SQLite / PostgreSQL 双后端兼容，见 §12.1，勿用 AUTOINCREMENT 字面量）
- 外键一律字符串形式 ForeignKey("表名.列名")
- 默认值走 server_default（与 backend/alembic/versions/ 手写迁移脚本保持一致）
- file_size 用 BigInteger：文档 DDL 的 INTEGER 在 PG 为 4 字节，装不下 >2G 的文件（电影上限 5G）
- 用非注解 mapped_column 风格：规避 SQLAlchemy 2.0.36 在 Python 3.14 下对
  Mapped[Optional[T]] 注解解析的兼容性缺陷（requirements.txt 已 pin，不可升级）
"""
from datetime import datetime

from sqlalchemy import (
    BigInteger,
    Boolean,
    DateTime,
    Float,
    ForeignKey,
    Identity,
    Index,
    Integer,
    String,
    Text,
    UniqueConstraint,
    false,
    func,
    text,
)
from sqlalchemy.orm import mapped_column

from app.database import Base

# 双后端主键类型（docs/新系统设计.md §12.1）：
# - PostgreSQL：BIGINT + Identity → GENERATED BY DEFAULT AS IDENTITY
# - SQLite：退化为 INTEGER（rowid 别名自增）；直接 BigInteger 主键在 SQLite 不会自增
BIG_PK = BigInteger().with_variant(Integer, "sqlite")


class Media(Base):
    """影视清单（承接旧 media 表）"""

    __tablename__ = "media"

    id = mapped_column(BIG_PK, Identity(), primary_key=True)
    title = mapped_column(Text, nullable=False)
    tmdb_id = mapped_column(Integer)
    media_type = mapped_column(Text)  # movie / tv
    # 线上反馈修复 Q2：影视海报相对路径（TMDB 图床 /t/p/w500/...），MediaAddView
    # 选中影视时随 POST /api/media 落库，影视库展示不再丢海报。仅存相对路径，
    # 不拼接图床地址（前端已有 TMDB_POSTER_BASE）。
    poster_path = mapped_column(Text, nullable=True)
    status = mapped_column(  # tracking/downloading/paused/error
        Text, nullable=False, server_default=text("'tracking'")
    )
    scan_interval_minutes = mapped_column(Integer, server_default=text("60"))
    max_episode_size_gb = mapped_column(Float)
    max_movie_size_gb = mapped_column(Float)
    in_emby = mapped_column(Boolean, server_default=false())
    last_scan_at = mapped_column(DateTime)
    created_at = mapped_column(DateTime, server_default=text("CURRENT_TIMESTAMP"))
    updated_at = mapped_column(
        DateTime,
        server_default=text("CURRENT_TIMESTAMP"),
        onupdate=func.current_timestamp(),
    )


class EpisodeState(Base):
    """单集派发状态（防重权威源，替代旧 config 表 JSON）"""

    __tablename__ = "episode_state"
    __table_args__ = (
        UniqueConstraint("media_id", "episode", name="uq_episode_state_media_episode"),
    )

    id = mapped_column(BIG_PK, Identity(), primary_key=True)
    media_id = mapped_column(BigInteger, ForeignKey("media.id"), nullable=False)
    episode = mapped_column(Text, nullable=False)  # S01E01 / 全量=文件名
    state = mapped_column(  # queued/transferring/downloading/done/failed
        Text, nullable=False
    )
    file_name = mapped_column(Text)
    file_size = mapped_column(BigInteger)
    share_code = mapped_column(Text)
    quark_path = mapped_column(Text)
    aria2_gid = mapped_column(Text)
    retry_count = mapped_column(Integer, server_default=text("0"))
    error = mapped_column(Text)
    updated_at = mapped_column(DateTime, onupdate=func.current_timestamp())


class TransferQueue(Base):
    """容量感知转存队列（执行流视图；防重权威源 = episode_state）"""

    __tablename__ = "transfer_queue"
    __table_args__ = (
        UniqueConstraint("media_id", "episode", name="uq_transfer_queue_media_episode"),
        Index("idx_tq_status", "status"),
        Index("idx_tq_media", "media_id"),
    )

    id = mapped_column(BIG_PK, Identity(), primary_key=True)
    media_id = mapped_column(BigInteger, ForeignKey("media.id"), nullable=False)
    episode = mapped_column(Text, nullable=False)
    file_name = mapped_column(Text, nullable=False)
    file_size = mapped_column(BigInteger, nullable=False)  # 字节
    share_code = mapped_column(Text, nullable=False)
    pwd_id = mapped_column(Text)
    stoken = mapped_column(Text)
    receive_code = mapped_column(Text)
    fids = mapped_column(Text)  # JSON 数组字符串
    fid_tokens = mapped_column(Text)
    folder_id = mapped_column(Text)
    status = mapped_column(  # pending/transferring/downloading/done/failed
        Text, nullable=False, server_default=text("'pending'")
    )
    quota_reject_count = mapped_column(Integer, server_default=text("0"))
    error = mapped_column(Text)
    # P2-10（council）：cloudSaver save 受理后返回的转存任务 id。
    # 作为 save 幂等标记——save 一受理即落此列，后续 get_link/add_uri 失败重试时
    # 不再重复调用 cloudsaver.save（防重复转存占空间 / cloudSaver 端重复任务），
    # 只继续等落盘/取直链。迁移见 alembic/versions/0002_save_task_id.py。
    save_task_id = mapped_column(Text)
    # P0-1（council）：最近一次 cloudSaver save 的受理时间（naive UTC）。
    # 仅用于重试时判断 save 受理是否超时（tasks/transfer.py 的
    # _SAVE_ATTEMPT_MAX_SECONDS 兜底）——save_task_id 存在但受理时间过久 → 强制
    # 重新 save，任何清空路径漏清也会在超时后自动恢复，杜绝盲等死循环。
    # 迁移见 alembic/versions/0005_save_attempt_at.py。
    save_attempt_at = mapped_column(DateTime)
    enqueued_at = mapped_column(DateTime, server_default=text("CURRENT_TIMESTAMP"))
    updated_at = mapped_column(DateTime, onupdate=func.current_timestamp())


class DownloadTask(Base):
    """aria2 下载任务跟踪"""

    __tablename__ = "download_task"

    id = mapped_column(BIG_PK, Identity(), primary_key=True)
    media_id = mapped_column(BigInteger, ForeignKey("media.id"))
    transfer_id = mapped_column(BigInteger, ForeignKey("transfer_queue.id"))
    episode = mapped_column(Text)
    file_name = mapped_column(Text)
    aria2_gid = mapped_column(Text)
    status = mapped_column(  # downloading/complete/failed
        Text, nullable=False, server_default=text("'downloading'")
    )
    local_path = mapped_column(Text)  # /downloads/...
    quark_path = mapped_column(Text)  # /quark/...（删除用）
    downloaded_at = mapped_column(DateTime)
    created_at = mapped_column(DateTime, server_default=text("CURRENT_TIMESTAMP"))


class TaskRun(Base):
    """任务执行记录（替代 n8n 执行历史）"""

    __tablename__ = "task_run"

    id = mapped_column(BIG_PK, Identity(), primary_key=True)
    task_type = mapped_column(Text, nullable=False)  # scan_media/transfer/...
    media_id = mapped_column(Integer)
    status = mapped_column(Text)  # success/skipped/error
    message = mapped_column(Text)
    started_at = mapped_column(DateTime)
    finished_at = mapped_column(DateTime)


class QuarkCapacityLog(Base):
    """容量快照归档（非实时数据源，实时判断在容量 provider）"""

    __tablename__ = "quark_capacity_log"

    id = mapped_column(BIG_PK, Identity(), primary_key=True)
    total_gb = mapped_column(Float)
    used_gb = mapped_column(Float)
    source = mapped_column(Text)  # cloudsaver/alist/estimated
    checked_at = mapped_column(DateTime, server_default=text("CURRENT_TIMESTAMP"))


class User(Base):
    """用户（注册/登录/审批）"""

    __tablename__ = "users"

    id = mapped_column(BIG_PK, Identity(), primary_key=True)
    username = mapped_column(Text, nullable=False, unique=True)
    password_hash = mapped_column(Text, nullable=False)
    role = mapped_column(  # admin / guest
        Text, nullable=False, server_default=text("'guest'")
    )
    invite_code = mapped_column(Text)  # 注册时使用的邀请码
    created_at = mapped_column(DateTime, server_default=text("CURRENT_TIMESTAMP"))


class InviteCode(Base):
    """邀请码"""

    __tablename__ = "invite_codes"

    code = mapped_column(Text, primary_key=True)
    created_by = mapped_column(BigInteger, ForeignKey("users.id"))
    used_by = mapped_column(BigInteger, ForeignKey("users.id"))
    used_at = mapped_column(DateTime)
    created_at = mapped_column(DateTime, server_default=text("CURRENT_TIMESTAMP"))


class WatchRequest(Base):
    """访客「想看」审批流"""

    __tablename__ = "watch_requests"

    id = mapped_column(BIG_PK, Identity(), primary_key=True)
    requested_by = mapped_column(BigInteger, ForeignKey("users.id"))
    title = mapped_column(Text, nullable=False)
    tmdb_id = mapped_column(Integer)
    media_type = mapped_column(Text)  # movie / tv
    poster_path = mapped_column(Text)
    status = mapped_column(  # pending/approved/rejected
        Text, nullable=False, server_default=text("'pending'")
    )
    reviewed_by = mapped_column(BigInteger, ForeignKey("users.id"))
    reviewed_at = mapped_column(DateTime)
    reject_reason = mapped_column(Text)
    created_at = mapped_column(DateTime, server_default=text("CURRENT_TIMESTAMP"))


class Notification(Base):
    """站内消息（InAppNotifier 持久化，前端铃铛）"""

    __tablename__ = "notifications"
    __table_args__ = (Index("idx_notif_recipient", "recipient", "is_read"),)

    id = mapped_column(BIG_PK, Identity(), primary_key=True)
    recipient = mapped_column(BigInteger, ForeignKey("users.id"))  # null=全体
    event_type = mapped_column(Text, nullable=False)  # download_complete/...
    title = mapped_column(Text, nullable=False)
    body = mapped_column(Text)
    is_read = mapped_column(Boolean, server_default=false())
    created_at = mapped_column(DateTime, server_default=text("CURRENT_TIMESTAMP"))


class SystemConfig(Base):
    """非敏感系统配置"""

    __tablename__ = "system_config"

    key = mapped_column(Text, primary_key=True)
    value = mapped_column(Text)
    updated_at = mapped_column(DateTime, server_default=text("CURRENT_TIMESTAMP"))


class TmdbCache(Base):
    """TMDB 元数据缓存（存字符串 TMDB id，title/poster 直接随源更新）

    tmdb_id 存字符串：TMDB API 返回的 id 本身是数字，但以字符串主键存储，
    便于兼容不同来源（搜索/详情）的取值，并规避前端大整数精度丢失问题。
    仅缓存新增影视/想看时的元数据，读写走 services/tmdb.py（并行开发中）。
    """

    __tablename__ = "tmdb_cache"

    tmdb_id = mapped_column(String(32), primary_key=True)  # 字符串 TMDB id
    title = mapped_column(String(512), nullable=False)
    media_type = mapped_column(String(32), nullable=False)  # movie / tv
    poster_path = mapped_column(Text, nullable=True)  # TMDB 图床相对路径 /t/p/w500/...
    year = mapped_column(Integer, nullable=True)
    updated_at = mapped_column(
        DateTime,
        server_default=text("CURRENT_TIMESTAMP"),
        onupdate=func.current_timestamp(),
    )
