"""initial schema: 11 张业务表

Revision ID: 0001_initial_schema
Revises:
Create Date: 2026-09-05

首版建表，与 backend/app/models/__init__.py 一一对应（手写，非 autogenerate）。
后续结构变更建议用 `alembic revision --autogenerate` 生成草稿后人工复核再提交。
"""
from typing import Optional, Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0001_initial_schema"
down_revision: Optional[str] = None
branch_labels: Optional[Sequence[str]] = None
depends_on: Optional[Sequence[str]] = None

# 双后端主键类型（与 backend/app/models/__init__.py 的 BIG_PK 一致）：
# - PostgreSQL：BIGINT + Identity → GENERATED BY DEFAULT AS IDENTITY
# - SQLite：退化为 INTEGER（rowid 别名自增；SQLAlchemy 的 sqlite 方言不渲染 IDENTITY）
_BIG_ID = sa.BigInteger().with_variant(sa.Integer, "sqlite")


def upgrade() -> None:
    # ---- media 影视清单 ----
    op.create_table(
        "media",
        sa.Column("id", _BIG_ID, sa.Identity(), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("tmdb_id", sa.Integer(), nullable=True),
        sa.Column("media_type", sa.Text(), nullable=True),
        sa.Column("status", sa.Text(), server_default=sa.text("'tracking'"), nullable=False),
        sa.Column("scan_interval_minutes", sa.Integer(), server_default=sa.text("60"), nullable=True),
        sa.Column("max_episode_size_gb", sa.Float(), nullable=True),
        sa.Column("max_movie_size_gb", sa.Float(), nullable=True),
        sa.Column("in_emby", sa.Boolean(), server_default=sa.false(), nullable=True),
        sa.Column("last_scan_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=True),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )

    # ---- episode_state 单集派发状态（防重权威源）----
    op.create_table(
        "episode_state",
        sa.Column("id", _BIG_ID, sa.Identity(), nullable=False),
        sa.Column("media_id", sa.BigInteger(), nullable=False),
        sa.Column("episode", sa.Text(), nullable=False),
        sa.Column("state", sa.Text(), nullable=False),
        sa.Column("file_name", sa.Text(), nullable=True),
        sa.Column("file_size", sa.BigInteger(), nullable=True),
        sa.Column("share_code", sa.Text(), nullable=True),
        sa.Column("quark_path", sa.Text(), nullable=True),
        sa.Column("aria2_gid", sa.Text(), nullable=True),
        sa.Column("retry_count", sa.Integer(), server_default=sa.text("0"), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["media_id"], ["media.id"]),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("media_id", "episode", name="uq_episode_state_media_episode"),
    )

    # ---- transfer_queue 容量感知转存队列 ----
    op.create_table(
        "transfer_queue",
        sa.Column("id", _BIG_ID, sa.Identity(), nullable=False),
        sa.Column("media_id", sa.BigInteger(), nullable=False),
        sa.Column("episode", sa.Text(), nullable=False),
        sa.Column("file_name", sa.Text(), nullable=False),
        sa.Column("file_size", sa.BigInteger(), nullable=False),
        sa.Column("share_code", sa.Text(), nullable=False),
        sa.Column("pwd_id", sa.Text(), nullable=True),
        sa.Column("stoken", sa.Text(), nullable=True),
        sa.Column("receive_code", sa.Text(), nullable=True),
        sa.Column("fids", sa.Text(), nullable=True),
        sa.Column("fid_tokens", sa.Text(), nullable=True),
        sa.Column("folder_id", sa.Text(), nullable=True),
        sa.Column("status", sa.Text(), server_default=sa.text("'pending'"), nullable=False),
        sa.Column("quota_reject_count", sa.Integer(), server_default=sa.text("0"), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("enqueued_at", sa.DateTime(), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["media_id"], ["media.id"]),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("media_id", "episode", name="uq_transfer_queue_media_episode"),
    )
    op.create_index("idx_tq_status", "transfer_queue", ["status"], unique=False)
    op.create_index("idx_tq_media", "transfer_queue", ["media_id"], unique=False)

    # ---- download_task aria2 下载任务 ----
    op.create_table(
        "download_task",
        sa.Column("id", _BIG_ID, sa.Identity(), nullable=False),
        sa.Column("media_id", sa.BigInteger(), nullable=True),
        sa.Column("transfer_id", sa.BigInteger(), nullable=True),
        sa.Column("episode", sa.Text(), nullable=True),
        sa.Column("file_name", sa.Text(), nullable=True),
        sa.Column("aria2_gid", sa.Text(), nullable=True),
        sa.Column("status", sa.Text(), server_default=sa.text("'downloading'"), nullable=False),
        sa.Column("local_path", sa.Text(), nullable=True),
        sa.Column("quark_path", sa.Text(), nullable=True),
        sa.Column("downloaded_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=True),
        sa.ForeignKeyConstraint(["media_id"], ["media.id"]),
        sa.ForeignKeyConstraint(["transfer_id"], ["transfer_queue.id"]),
        sa.PrimaryKeyConstraint("id"),
    )

    # ---- task_run 任务执行记录 ----
    op.create_table(
        "task_run",
        sa.Column("id", _BIG_ID, sa.Identity(), nullable=False),
        sa.Column("task_type", sa.Text(), nullable=False),
        sa.Column("media_id", sa.Integer(), nullable=True),
        sa.Column("status", sa.Text(), nullable=True),
        sa.Column("message", sa.Text(), nullable=True),
        sa.Column("started_at", sa.DateTime(), nullable=True),
        sa.Column("finished_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )

    # ---- quark_capacity_log 容量快照归档 ----
    op.create_table(
        "quark_capacity_log",
        sa.Column("id", _BIG_ID, sa.Identity(), nullable=False),
        sa.Column("total_gb", sa.Float(), nullable=True),
        sa.Column("used_gb", sa.Float(), nullable=True),
        sa.Column("source", sa.Text(), nullable=True),
        sa.Column("checked_at", sa.DateTime(), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )

    # ---- users 用户 ----
    op.create_table(
        "users",
        sa.Column("id", _BIG_ID, sa.Identity(), nullable=False),
        sa.Column("username", sa.Text(), nullable=False),
        sa.Column("password_hash", sa.Text(), nullable=False),
        sa.Column("role", sa.Text(), server_default=sa.text("'guest'"), nullable=False),
        sa.Column("invite_code", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("username", name="uq_users_username"),
    )

    # ---- invite_codes 邀请码 ----
    op.create_table(
        "invite_codes",
        sa.Column("code", sa.Text(), nullable=False),
        sa.Column("created_by", sa.BigInteger(), nullable=True),
        sa.Column("used_by", sa.BigInteger(), nullable=True),
        sa.Column("used_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=True),
        sa.ForeignKeyConstraint(["created_by"], ["users.id"]),
        sa.ForeignKeyConstraint(["used_by"], ["users.id"]),
        sa.PrimaryKeyConstraint("code"),
    )

    # ---- watch_requests 访客「想看」审批流 ----
    op.create_table(
        "watch_requests",
        sa.Column("id", _BIG_ID, sa.Identity(), nullable=False),
        sa.Column("requested_by", sa.BigInteger(), nullable=True),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("tmdb_id", sa.Integer(), nullable=True),
        sa.Column("media_type", sa.Text(), nullable=True),
        sa.Column("poster_path", sa.Text(), nullable=True),
        sa.Column("status", sa.Text(), server_default=sa.text("'pending'"), nullable=False),
        sa.Column("reviewed_by", sa.BigInteger(), nullable=True),
        sa.Column("reviewed_at", sa.DateTime(), nullable=True),
        sa.Column("reject_reason", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=True),
        sa.ForeignKeyConstraint(["requested_by"], ["users.id"]),
        sa.ForeignKeyConstraint(["reviewed_by"], ["users.id"]),
        sa.PrimaryKeyConstraint("id"),
    )

    # ---- notifications 站内消息 ----
    op.create_table(
        "notifications",
        sa.Column("id", _BIG_ID, sa.Identity(), nullable=False),
        sa.Column("recipient", sa.BigInteger(), nullable=True),
        sa.Column("event_type", sa.Text(), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("body", sa.Text(), nullable=True),
        sa.Column("is_read", sa.Boolean(), server_default=sa.false(), nullable=True),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=True),
        sa.ForeignKeyConstraint(["recipient"], ["users.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_notif_recipient", "notifications", ["recipient", "is_read"], unique=False)

    # ---- system_config 非敏感配置 ----
    op.create_table(
        "system_config",
        sa.Column("key", sa.Text(), nullable=False),
        sa.Column("value", sa.Text(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=True),
        sa.PrimaryKeyConstraint("key"),
    )


def downgrade() -> None:
    # 索引需先于对应表删除（表删除后索引随之消失，顺序颠倒会报 no such index）
    op.drop_index("idx_tq_status", table_name="transfer_queue")
    op.drop_index("idx_tq_media", table_name="transfer_queue")
    op.drop_index("idx_notif_recipient", table_name="notifications")
    op.drop_table("system_config")
    op.drop_table("notifications")
    op.drop_table("watch_requests")
    op.drop_table("invite_codes")
    op.drop_table("users")
    op.drop_table("quark_capacity_log")
    op.drop_table("task_run")
    op.drop_table("download_task")
    op.drop_table("transfer_queue")
    op.drop_table("episode_state")
    op.drop_table("media")
